source 'http://rubygems.org'

gem 'rails', '3.0.0'
gem 'mysql2'
gem 'devise'
gem 'jquery-rails'
gem 'cancan'
gem 'friendly_id'
gem 'eutils'
gem 'libxml-ruby', :require => 'libxml'
gem 'bio'
gem 'activerecord-import'
gem 'will_paginate', '3.0.pre2'